version: "3.9"
services:
  webapp:
    restart: always
    build:
      context: ./grid-react
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./grid-react:/app
    ports:
      - 5173:5173
